npm/marky-markdown

index.js
lib/sanitize.js
test/index.js

Fixes https://github.com/npm/marky-markdown/issues/9

add `allowScriptTags` option, disabled by default.

---

test/index.js

Without squiggle the assert checks "string not at beginning" instead of "string is present"

Add missing squiggles to tests

---

index.js
lib/render.js
lib/sanitize.js
package.json
test/index.js

This PR is doing two things at once:
- replace marked with markdown-it for better performance and stability
- replace pygments-bundled with highlights for, well, better performance and stability
@bcoe if you end up working on this, notice that I started a span whitelist, but it's still missing some of the tokens: https://github.com/atom/highlights/issues/13

[WIP] start using markdown-it and highlights

---

README.md
example.js
index.js
lib/render.js
package.json
test/fixtures.js
test/index.js

Per @rockbot's request today, marky-markdown has gone back to its old synchronous API. This is possible because we replaced the async `pygments-bundled` syntax highlighter with `highlights`. This will allow us to keep all of newww's presenters synchronous and consistent across different models like `Package`, `User`, and `Customer`. Plus the sync API is just way simpler.
I also updated the fixtures and "real readmes in the wild" section of the tests to [automatically pull in the READMEs](https://github.com/npm/marky-markdown/blob/c41dbfaa6379add26cf3465aa1d30de7d9d0b6b6/test/fixtures.js#L13-L28) of everything in `dependencies` and `devDependencies`, so testing any wonky package READMEs in the future will be a simple matter of `npm i -D that-wonky-package`.
This is a major change, so we'll …

make it synchronous again, now that pygments is out of the mix

---

bin/marky-markdown.js

Apparently CLI is out-of-date now. This is a quick fix.
Also, shouldn't the main module throw errors rather that returning them?

Update CLI to use the synchronous API

---

package.json

This fixes a bug evidenced in it's own changelog on npm: https://www.npmjs.com/package/sanitize-html#changelog -- a code block that just contains `undefined` will be squashed to an empty string.

Update sanitize-html to 1.6.1

---

bin/marky-markdown.js

Since 40cf5f7 there is no point in this check.

Remove instanceof Error check from CLI

---

index.js

[`assert`](http://nodejs.org/api/assert.html) is not supposed to be used outside unit tests.
> This module is used for writing unit tests for your applications
Using this module in regular code adds an extra dependency that needs to be shimmed in other environments ([browserify shim](https://github.com/defunctzombie/commonjs-assert/blob/master/assert.js) is pretty huge) and most of its methods won't make sense anyway (`throws`, `deepEqual`, `fail`).
Simple `throw` statement here is more than enough.

Don't assert() outside unit tests

---

index.js
lib/packagize.js
test/index.js

npmjs.com package pages will soon have a nav for moving between the package info page and the package access page. This nav will likely sit in the HTML between the package name and the start of the readme itself, so we need more flexibility around how and where package name and description are rendered.
This PR stops injecting package name and description into the readme, leaving it up to www to render the name and description as it sees fit, using the newly exported `marky.parsePackageDescription()` method to continue safely supporting markdowny descriptions.

stop injecting package metadata into the readme

---

lib/sanitize.js

Because I have a module, that has a complex table in it...
By the way, any reason the styling of tables on npm site is the way it is? Github centers (or, rather, does not reset to `left`) the `th`. Also, borders do help... 
Compare:
https://www.npmjs.com/package/gampee#params
vs
https://github.com/insidewarehouse/gampee#params

Allow `colspan`/`rowspan` on table cells

---

lib/sanitize.js
test/fixtures/dirty.md
test/index.js

I filed an issue (in hindsight, for the wrong repo) at npm/newww#1107. In short width, height, and valign attributes are allowed on github and disallowed on npmjs.com which makes it rather difficult to achieve visual consistency between the two.
Some examples:
- https://www.npmjs.com/package/gulp-markdown-equations vs. https://github.com/rreusser/gulp-markdown-equations (update: tried SVG on this one, proxying it through rawgit.com to get around strange and seemingly unnecessary github security restrictions)
- https://www.npmjs.com/package/fly vs. https://github.com/flyjs/fly
- https://www.npmjs.com/package/ndarray-blas-level1 vs. https://github.com/scijs/ndarray-blas-level1
Basically any image with a fixed width and height loses it when published to npm (i.e. the only non-css way to use …

Allow width, height, and valign attributes on img tags

---

lib/sanitize.js
test/fixtures/dirty.md
test/index.js

The markdown-it parser supports [GFM-style strikethrough](https://github.com/markdown-it/markdown-it#syntax-extensions), but the `<s>` element was not allowed by marky-markdown's sanitizer. This PR adds it to the whitelist.
> The HTML Strikethrough Element (`<s>`) renders text with a strikethrough, or a line through it. Use the `<s>` element to represent things that are no longer relevant or no longer accurate.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element
Fixes https://github.com/npm/newww/issues/1065; cc @jamestalmage

add support for ~~strikethrough~~

---

lib/render.js
package.json
test/fixtures/lazyheading.md
test/index.js

This little update handles issue #39 by using the [markdown-it-lazy-headers](https://www.npmjs.com/package/markdown-it-lazy-headers) module to allow authors to omit the (technically required, per the [CommonMark Spec](http://spec.commonmark.org/0.17/#atx-headers)) space(s) between the leading `#` character(s) and the heading text. It includes a short test fixture as well.
Prior to this update, `#hello` gets rendered as `<p>#hello</p>`, but now it becomes a proper `<h1>hello</h1>`. Likewise for `h2`–`h6`.

Add support for markdown headings lacking spaces between the #(s) and heading text

---

lib/sanitize.js
test/fixtures/dirty.md
test/index.js

Per issue #55, this update white lists a few HTML elements from [GitHub's whitelist](https://github.com/jch/html-pipeline/blob/2a55955b5da482624df95ff5cf88ba7ff522e97a/lib/html/pipeline/sanitization_filter.rb#L112). Most of the elements in that list are already allowed, so this just adds `del`, `ins`, `sub`, and `sup` (and it alphabetizes the array for `allowedTags`). There's also a simple test fixture for each.

Whitelist the ins, del, sub, and sup HTML elements

---

README.md
index.js
lib/render.js
package.json
test/index.js

This is a followup to #19, opened from my fork because I no longer have commit access to the canonical repo. When enabled, the linkify feature automatically converts fully-qualified URLs (in inline text) into links:
Markdown before:
```md
My favorite website is http://zombo.com
```
HTML after:
```html
<p>My favorite website is <a href="http://zombo.com">http://zombo.com</a><p>
```
The linkify feature is enabled by default. To disable it, set an option:
```js
marky(myText, {linkify: false})
```
This update exposes the [`linkify` option from markdown-it](https://github.com/markdown-it/markdown-it#linkify), which is powered by the standalone [linkify-it](https://github.com/markdown-it/linkify-it) module. The `maintenance-modules` devDependency is added because it happens to be a package with …

linkify fully-qualified URLs (redo)

---

lib/headings.js
package.json
test/fixtures/github.md
test/index.js

Thanks for sharing this package, its quite useful! :)
I noticed that `marky-markdown` is not consistent with GitHub when generating anchor IDs. Specifically, its filtering out underscores and trailing dashes, which are left alone on GitHub.
Here is what I saw coming out of `marky-markdown`:
```
> var md = require('marky-markdown')
> md('## test(\n## test)\n## test_\n## test-\n## test=\n').html()
```
```html
<h2 id="user-content-test" class="deep-link"><a href="#test">test(</a></h2>
<h2 id="user-content-test" class="deep-link"><a href="#test">test)</a></h2>
<h2 id="user-content-test" class="deep-link"><a href="#test">test_</a></h2>
<h2 id="user-content-test" class="deep-link"><a href="#test">test-</a></h2>
<h2 id="user-content-test" class="deep-link"><a href="#test">test=</a></h2>
``` …

make slugs behave more like GitHub

---

lib/highlights-tokens.js
lib/render.js
lib/sanitize.js
package.json
test/fixtures/basic.md
test/index.js

Yaks be shaved, this should take care of #64:
* The stock [highlights](https://github.com/atom/highlights) package we use for syntax highlighting doesn't include a grammar for diffs. Its existing grammars are mostly automatically converted from TextMate grammars, and TM _does_ have a diff one, so I converted it myself and published it to NPM as [atom-language-diff](https://www.npmjs.com/package/atom-language-diff), then added it as a dependency here.
* I discovered that the HTML sanitizer was wrecking the generated output. It turns out that the [highlights-tokens](https://www.npmjs.com/package/highlights-tokens) package, where we get a list of allowed class names, generates the token list by analyzing the `highlights` package's generated grammar objects. So I added a build step to …

Support diff syntax highlighting

---

lib/render.js
test/fixtures/github.md
test/index.js

Here's a tiny PR that disables the "shortcut" handling in the `markdown-it-emoji` plugin we use for emoji support; fixes the issues pointed out as per #95.
This isn't directly compatible with #96 due to the rearranging I did there, but it's a pretty trivial modification to merge between the two; I'm happy to update whatever as needed.

Disable smiley shortcut handling in markdown-it-emoji

---

lib/render.js
package.json

Apologies if I'm pushing ahead too quickly on this, but greenkeeper reported in #105 that switching to lodash 4 breaks the build; turns out all we need to do is call `_.pickBy()` rather than `_.pick()` when we're resolving languages in the code highlighting stuff.

Update to lodash 4.0, handle its breaking changes

---

lib/packagize.js
test/fixtures/burblewibble.md
test/index.js

I think the issue in #48 is that the similarity checker has no knowledge of scoped package names. If we add a line of code that does a regex match to filter out anything between a leading `@` and the first `/` (is that logic correct? Please double check my assumptions), then the packagizer code correctly applies `class='package-name-redundant'` to the generated H1.
I tested this against [@sindresorhus/df](https://www.npmjs.com/package/@sindresorhus/df) and [@aredridel/redis-mock](https://www.npmjs.com/package/@aredridel/redis-mock).

Ignore package scope when calculating header/name similarity

---

package.json

i know this might seem weird, but the package author should be the name of the maintainer imo, and i'm playing that role now. 
additionally, the list of contributors was very out of date. contributors will now be recognized in the changelog for the sake of keeping the `package` short.
fixes #111

remove contributors section, change author to ashley

---

package.json
test/fixtures.js
test/fixtures/readmes/async.md
test/fixtures/readmes/benchmark.md
test/fixtures/readmes/cicada.md
test/fixtures/readmes/express.md
test/fixtures/readmes/grunt-angular-templates.md
test/fixtures/readmes/johnny-five.md
test/fixtures/readmes/maintenance-modules.md
test/fixtures/readmes/memoize.md
test/fixtures/readmes/mkhere.md
test/fixtures/readmes/payform.md
test/fixtures/readmes/wzrd.md
test/index.js

A bunch of our `devDependencies` are only included so we can use their README data as test fixtures. This commit adds their READMEs as static files we load separately during `npm test` and gets rid of their entries in `package.json`. As far as I can tell, we only need `mocha`, `standard`, and `glob` for actual development.
The overall testing strategy is similar to what we already have, except instead of loading all of the markdown strings in `fixtures.packageNames` we split them into `fixtures.dependencies` (which may be a poor name, since it *does* also include the `devDependencies` as well) and `fixtures.examples`. This allows us to differentiate them during test runs because we don't have to try to `require()` the static fixtures' packages; we can just mock them as `{name: name}`. …

Overhaul devDependencies' readme parsing test strategy

---

lib/sanitize.js
test/fixtures/basic.md
test/index.js

Prior to this commit, any URL containing "//youtube.com" would make it through our filter, but the intent was to only allow actual YouTube URLs. So now we're more explicit about requiring that "//youtube.com" either starts the string, or is preceded by "http:" or "https:". We've also got some test updates to make sure URLs previously wrongly allowed get filtered out, plus that a full URL where the "//" doesn't appear at the very beginning still works.
Fixes #108.

Tighten up the YouTube filter regex

---

lib/comments.js

We have a tiny module `lib/comments.js` that strips HTML comments from its input, but we haven't been using it since [16696d2](https://github.com/npm/marky-markdown/commit/16696d206dd95e3594a0dbcdbf20271cffaa71d3) (and the `require()` for it was commented out in [6a80d2e](https://github.com/npm/marky-markdown/commit/6a80d2e0b553447d10fc012fd444b3e3e66d908f)). So here we finish the job and remove the file itself.

Remove unused HTML comment remover

---

README.md
package.json

We still had `html-frontmatter` listed as a dependency in the README, and a `frontmatter` keyword in package.json, but those are out of date now, no? This commit cleans them up.

Remove final references to frontmatter

---

package.json
test/fixtures.js

Closes #139 
Closes #140 
Closes #141
Closes #142 
Closes #143 
Hello! This PR updates `marky-markdown` to the new major version of `standard`. 
The two notable updates for this repo are:
- `standard-format` must not be installed and used separately. Updated the test script to run it along with `standard`
- The file `fixtures.js` was updated to abide the new rule: 
- `Use path.join() or path.resolve() instead of + to create paths. (no-path-concat)`
Cheers!

update to standard@6.0.4

---

README.md

I was thinking it might be appropriate to call out the `:emoji:` conversion we do, in the list describing what marky does.

Add a line about :emoji: conversion to the README

---

lib/packagize.js
package.json
test/cdn.js
test/fixtures/github.md
test/marky.js

I decided to take a look at our test coverage to see if there were any substantial gaps, so I ran our tests through istanbul and found just a small handful of lines that weren't covered. The changes in this PR cover most of it.
**Please note that I didn't actually add the code coverage machinery.** It's certainly something we could do if everybody wanted to, but I was just after the data so I ran it as a one-off by doing `npm install istanbul` followed by `./node_modules/istanbul/lib/cli.js cover node_modules/mocha/bin/_mocha -- -R spec` and opening `./coverage/lcov-report/index.html` in a browser.
The changes:
- Probably the most important one is where our `packagize` module would error out if the package provided lacked a name (because it would try to do `pkg.name.replace(...)` on an …

Increase test coverage

---

lib/code-wrap.js
lib/render.js
lib/sanitize.js
package.json
test/markdown.js
test/marky.js
test/sanitize.js

As of `markdown-it` 5.1.0, we no longer have a `<pre><code>...</code></pre>` wrapper on fenced code blocks; this PR updates the tests that fail as a result of that change, plus removes a couple that were specifically looking for `class="highlight"` on said `<code>` elements.
If/when this is merged, the root of the rendered code blocks will be `<pre class="editor">`, and lots of dependents' CSS will need updated.

Update tests to support markdown-it 5.1.0

---

lib/render.js
package.json
test/fixtures/basic.md
test/markdown.js

In #126 we have, among other things, a couple of rendering issues caused by the fact that [markdown-it](https://www.npmjs.com/package/markdown-it) (probably correctly) doesn't do anything with tab characters in fenced code blocks; *and* browsers render them with the traditional eight character width, and sometimes visually collapse sequential tabs into one. Neither of these behaviors matches what GitHub does, which appears to be four-space substitution per leading tab.
I couldn't find anything in the markdown-it plugin ecosystem that already covered this, so I built a markdown-it plugin called [markdown-it-expand-tabs](https://www.npmjs.com/package/markdown-it-expand-tabs) that we can use to help fix these rendering glitches. It's on NPM now, so this PR pulls it in and updates the …

Convert leading tabs to spaces in fenced code blocks

---

lib/code-wrap.js

The highlighted code block wrapper plugin we wrote for markdown-it had the beginnings of support for customizing the wrapper tag, but there was no way to change it from consuming code, and no tests that covered using a custom tag. Since doing it would force users to skip the HTML sanitizing step (because anything other than a `div` will get filtered out), it seems just as well to remove that stuff for now.

Remove extraneous code block wrapper customization code

---

package.json

til we get #157 fixed. r? @revin

hold github-url-to-object at 2.1.0

---

test/fixtures/basic.md
test/markdown.js

This should fulfill the request from #160

Add tests to prove we aren't doing mustache template variable replacement

---

package.json
test/fixtures.js
test/marky.js

This takes #181 (thanks, @aredridel!) and rebases it onto the changes from #184 because the tests don't work at all until that's merged. It also makes the [`.equal()`/`.deepStrictEqual()` change](https://github.com/npm/marky-markdown/pull/181#discussion_r64114887) I talked about.

Test leak variable

---

lib/headings.js
test/fixtures/dirty.md
test/headings.js

Should fix #200. We don't touch the inline HTML link, so there won't be any generated link that points to the slug generated for the heading's `id` attribute, but we won't double-wrap anymore, so that seems like a good tradeoff.

Fix heading link generation when inline HTML links exist

---

lib/linkify.js
lib/render.js
test/markdown.js

This change moves us toward parity with Github's linkification of raw domain/hostnames by disabling the `fuzzyLink` option in markdown-it's linkification code, which is the code responsible for creating links from domains/hostnames without a protocol specifier (i.e., *example.com*). It will still create normal links from fully-qualified URLs (*http://example.com/*) and `mailto:` from email addresses (*marky@example.com*). Since GH linkifies hostnames starting with `www.` (www.example.com), we need to add our own schema/rule covering this case.
**Note:** This isn't done; I'll remove the WIP label when it's ready for review.

Github-style host/domain linkification

---

lib/render.js
test/markdown.js

Hey @ashleygwilliams if you agree with the premise from #162, then here's code that omits the fenced code block wrapper when syntax highlighting is off.
(I assume this would go in at the next major version bump)

Skip wrapping fenced code blocks when highlightSyntax === false

---

lib/gfm/relaxed-link-reference.js
lib/render.js
test/fixtures/link-ref-relaxed.md
test/fixtures/link-ref.md
test/markdown.js

Here's one way to handle #159.
It's a little bit hacky. I wrote up why in a comment in `lib/relaxed-link-reference.js`, but the short version is, there were a few ways to do this, none of which is really clean:
1. Re-wire markdown-it's internal parsing rules such that [link reference definitions](http://spec.commonmark.org/0.24/#link-reference-definitions) be allowed to interrupt paragraphs (which is explicitly disallowed by the specification, but which GitHub allows). The fragility here is that this requires using a few unofficial/internal APIs, so there's no guarantee it'll continue to work as-is down the road.
1. Add our own "new" parsing rule via public API. The rule would be basically a copy/paste of markdown-it's existing [reference](https://github.com/markdown-it/markdown-it/blob/ma …

Relaxed link reference definitions

---

lib/sanitize.js
test/fixtures/dirty.md
test/sanitize.js

Fixes the titular part of #169 by allowing `<dl>`, `<dt>`, and `<dd>` to pass through the sanitizer.
It's just the [one commit, 8806d0e](https://github.com/npm/marky-markdown/commit/8806d0e97ca9d888785999d939cc8063743c0346). For ease of sequencing, I've rebased this on top of #168; however, the more of these i do, the more confusing the change list for each PR looks. If you'd prefer me to do these a different way, I surely can. (Maybe a working branch for 8.0 would work better?)

Definition list support

---

README.md
lib/render.js

This change should make it possible to use marky-markdown with
browserify as long as the {highlightSyntax: false} option is used.
Using with {highlightSyntax: true} would generate a runtime error
in the browser.
Example command:
browserify main.js -i highlights > bundle.js
Also note that by not including the highlights library, the file
size of the resulting bundle is reduced by half.
Would close #46

Dont require 'highlights' in browserify environment.

---

CHANGELOG.md
package.json
test/markdown.js

This ends up changing how syntax highlighted JS code renders, so it requires a test update.
**Note** that as of this writing, `highlights@1.4.0` isn't actually out yet, just `1.4.0-candidate`, for testing purposes. Once the final one is published, we can merge this.

Bump highlights to 1.4.0

---

README.md

fixes #213 
the README was too focused on how marky works, not how to use marky. this PR reorders the sections to privilege users of marky over developers of marky. also it gives an intro which better summarizes what marky is, and is trying to be.

reorganize and update readme

---

README.md

I noticed the links to the GitHub docs on markdown are broken, so I fixed them.

Fix broken links to GitHub documentation

---

README.md
dist/marky-markdown.js
index.js
lib/gfm/indented-headings.js
lib/heading-links.js
lib/headings.js
lib/render.js
lib/sanitize.js
lib/token-util.js
test/emoji.js
test/fixtures/dirty.md
test/headings.js
test/sanitize.js

This stops marky from parsing ATX (i.e., single line `#`-style) markup as headings if there's leading whitespace before the `#` character. It's not CommonMark, but it's how GitHub does it.
Because of the similarity in internal module naming going on, I've rebased this on top of #225, so merge that first. This PR is really just one commit.
Fixes #233.

GitHub-style (non-)parsing of indented headings

---

README.md
dist/marky-markdown.js
index.js
lib/heading-links.js
lib/headings.js
lib/render.js
lib/sanitize.js
lib/token-util.js
test/emoji.js
test/fixtures/dirty.md
test/headings.js
test/sanitize.js

implement github style link headers

---

lib/sanitize.js
test/fixtures/dirty.md
test/sanitize.js

Fixes #241 by allowing the `align` attribute on `<p>` elements to make it through the sanitizer.

Allow `align` attribute on `<p>` elements

---

lib/heading-links.js
package.json

Hey @ashleygwilliams please look this over first, but I think this works for taking cheerio out of the process by which we generate heading link IDs.
I have a local cache of the entire npm package repository's README files that I pulled a few days ago using a modified readme-tester, and I ran marky against the first 100,000 files (which come in sorted alphabetically by package name). The difference before/after this change is small, but it looks like 0.5–1ms per readme on average, so it's something. It's not remotely enough for #149 to be done, but it's a step in the right direction. I think?

Replace cheerio-based heading ID processing with custom string processor

---

lib/sanitize.js
test/fixtures/dirty.md
test/sanitize.js

Fixes #269. I'll do this in #251 as well, in which case this one will become redundant (but it's here in case we don't merge it for 9.0 for any reason)

Allow `align` attribute on `<img>` elements

---

bin/marky-markdown.js

Cheerio object is no longer returned from marky as referenced in this commit:
https://github.com/npm/marky-markdown/commit/30865e4c37fae402d9e18b83a669bf8103259d27#diff-168726dbe96b3ce427e7fedce31bb0bcR40
I was getting the following error running the bin/marky-markdown script from the repo:
> /Users/sjking/repos/marky-markdown/bin/marky-markdown.js:16
>   process.stdout.write($.html())
>                          ^
> 
> TypeError: $.html is not a function
>   at /Users/sjking/repos/marky-markdown/bin/marky-markdown.js:16:26
>   at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

Update bin/marky-markdown to simply output the html string returned from marky.

---

index.js
lib/render.js

Here's a speculative change that adds a new public API:
Returns a marky-markdown-flavored markdown-it parser object. You can attach other markdown-it plugins, inspect the internals for debugging, etc... For example:
```js
var marky = require('marky-markdown')
var someMarkdownItPlugin = require('some-fake-markdown-it-plugin')
var parser = marky.getParser({ package: somePackage, highlightSyntax: false })
parser.use(someMarkdownItPlugin)
var html = parser.render(html)
```
`marky.getParser(options).render(markdown)` is the exact same thing as the existing `marky.render(markdown, options)`

Add new getParser public API

---

README.md
index.js
test/marky.js

Here are docs and tests for #286. This also updates the parser object returned by `getParser` such that it will sanitize the generated HTML when `{sanitize: true}` is passed (or not specified; it's the default).

Add tests and documentation for getParser

---

lib/plugin/heading-links.js
lib/sanitize.js
test/headings.js
test/htmlheading.js

use `anchor` as class name instead of `deep-link`

---

lib/plugin/github.js
test/fixtures/github.md
test/repo-github.js

Fixes #320 by also scanning `html_block` tokens for links & images to rewrite with GitHub URLs

Add html_block github image/link replacer

---

lib/sanitize.js
test/sanitize.js

Allow <details> and <summary> elements through sanitizer

---

README.md

Use innerHTML rather than innerText in the README

---

lib/plugin/code-wrap.js
lib/render.js
test/markdown.js

This gets us closer to github rendering by omitting the wrapping `<div>` and skipping the syntax highlighter on code fences that don't have a language provided, e.g.,
````
```
something()
```
````
Fixes #318

Skip syntax highlighting on code fences having no language specified

---

lib/gfm/indented-headings.js
test/headings.js

This fixes a bug in the indented-headings plugin where we were dropping the parsing rule's `alt` value, which is what tells markdown-it which rules can interrupt which other rules without requiring a terminating blank line.
Fixes #324

Allow headings to interrupt paragraphs.

---

lib/gfm/abstemious-html-block.js
lib/render.js
test/fixtures/abstemious-html-block.md
test/markdown.js

Here's a markdown-it plugin and tests to cover what's in #317, where we have markdown appearing after an HTML block without the CommonMark-mandated blank line in between.
This is fairly tricky, because the reasoning behind CommonMark's behavior here is completely sensible: once an HTML block is started, how can we tell it's actually finished? What this PR does is check to see if the lines in the parsed HTML block match any of the higher priority "block" type markdown parsing rules (list, heading, etc...), and if so, adjusts the parsing state to cut the HTML block off at the first sight of valid markdown.
Note that this only works its magic on "block" type rules. Before this PR, the following gets parsed as one big `html_block` token:
```markdown
- item 1
- item 2
```
and now that's an …

Non Greedy HTML Block Parsing

---

lib/gfm/image.js
lib/gfm/link.js
lib/render.js
test/markdown.js

It's kind of a bummer, but the type of looser parsing github does on links and images requires us to completely overwrite the markdown-it image and link rules. So, here it is.
Fixes #328

Allow whitespace between image/link labels and paths

---

bin/build-marky-info.js
index.js
marky.json
package.json
test/marky.js

Fixes #344.
This does result in the contents of our package.json being included in the browserify build. Do we care about that at all?

Add comment with marky version and issues URL to rendered HTML in debug mode

---

lib/sanitize.js
package.json
test/markdown.js

* Updates to markdown-it-task-lists 2.0
* Fixes a couple of tests that broke because of the changed markup (`.contains-task-list` rather than `.task-list` on the list elements)
* Updates the sanitizer accordingly

Bump markdown-it-task-lists to 2.0.0

---

package.json

At least for now, we still support node 4, which means oniguruma 6.2 breaks our build because it requires ES6 features. It's a dependency of a dependency, but if we add 6.1.1 explicitly as a devDependency, marky still works on node 4. So here's that.

Add oniguruma 6.1.1 explicitly as a devDependency to keep node 4 working

---

lib/plugin/github.js
lib/sanitize.js
test/repo-github.js

Fixes #368 by falling back to `opts.package.repository` if `opts.package.repository.url` is falsy.

Support shortcut github paths in URL rewrites

---

CHANGELOG.md

working on drafting the CHANGELOG for a 10.x release -- can't wait to try out some of @revin's changes that bring us closer to GitHub flavored markdown on npmjs.com; the impetus partially being that @zkat and myself are bumping into some rendering issues on our own READMEs.
How would folks feel about moving to http://conventionalcommits.org/ for future releases, so that CHANGELOG generation is less tedious.

chore: working on drafting a 10.x release

---

.travis.yml

Now that [node 8](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.0.0) is out, may as well use it in CI

Use node 8 on travis CI

---

lib/sanitize.js

This is the only place I found that broke browserify. Hopefully that's all there is; I didn't read every single line of code in the project 😛 
Fixes #371

Change ES6 object shorthand to ES5 so browserify bundle works

---

README.md
index.js
lib/plugin/heading-links.js
lib/sanitize.js
test/headings.js

this pull allows the classname used for heading anchors to be configured, this allows the npm website to continue using the old class-name (otherwise we would either need to support both class names, or re-render the whole set of README files).

feat: heading anchor class to be configured

---

lib/plugin/heading-links.js

Gets the browserify bundle working again; I keep missing these types of changes

Convert ES6 template string to ES5 in heading-links

---

lib/gfm/abstemious-html-block.js
package-lock.json
package.json
test/fixtures/abstemious-pathology.md
test/markdown.js

Found the issue causing an infinite loop in long documents with many consecutive HTML blocks; the rule wasn't doing an early exit when invoked in silent mode (which invocation happens when rules call other rules and only want to know if they match, without mutating the parsing state).
This also drastically speeds up rendering said documents, which is nice. I didn't make any official timing comparisons, but while hunting this down I instrumented the plugin with a silly level of logging output, and the test runs had on the order of 50x fewer lines in the logging because this fixes what ends up being a silly amount of recursion. Bonus!
Fixes #381

Fix infinite loop in abstemious HTML plugin

---

package.json

use standard-version's fancy-pants new lifecycle scripts to reenable the build step.

chore: add build step using standard-version's new lifecycle scripts

---

lib/gfm/override-link-destination-parser.js
test/markdown.js

Our customized link destination parser which allows link destinations to contain spaces was only considering `'` and `"` to be proper title delimiters; per CommonMark & GFM, we should allow `(` as well.
Fixes #384

Allow link titles to be delimited by parentheses

---

package-lock.json
package.json
test/repo-github.js

This will pass once https://github.com/zeke/github-url-to-object/pull/29 is merged/published in github-url-to-object; having this test in marky will verify that it continues to work 😄 
Fixes #386

Explicitly test for falsy repository.url in package

---

README.md

Update webpack part

---

lib/plugin/language-alias.js
lib/render.js
test/fixtures/basic.md
test/markdown.js

This _almost_ worked by adding a language mapping to the `render` module, but the wrapping `<div>` element for the rendered code block still had `class="highlight bash"` rather than `class="highlight sh"`, so I wrote a tiny markdown-it plugin to allow us to set up language aliases for code fence rendering.
Fixes #400

Treat `bash` the same as `sh` for specifying code fence language

---

.travis.yml
lib/plugin/language-alias.js
lib/render.js
lib/sanitize.js
package-lock.json
package.json
test/cdn.js
test/fixtures/basic.md
test/markdown.js

This will add support for highlighting JSX code blocks, once [highlights#55](https://github.com/atom/highlights/pull/55) is merged upstream.
Fixes #395

Add support for JSX syntax highlighting in code blocks

---

lib/sanitize.js
test/fixtures/basic.md
test/markdown.js

To finish off full support for TypeScript syntax highlighting, we need to add `ts` to the sanitizer safelist, and write some tests; here it is.
I've done `assert.equal($('.highlight.typescript').length, 0)` in two separate tests intentionally here, just because I decided that if our highlighter _isn't_ coercing `typescript` code fences to `ts` in the generated markup, that circumstance should break both of those tests. IMHO.
Fixes #397.

Add support/tests for typescript highlighting

---

package-lock.json
package.json

oniguruma released a minor version that broke node 4 support. version 7 returns node 4 support. this PR bumps onig to that version.

feat(dep): bump oniguruma

---

package.json

It looks like sanitize-html is outdated and has some security vulnerabilities. 
This PR bumps that package to the latest version.

Bump sanitize-html version

---

README.md
index.js
lib/plugin/nofollow.js
lib/render.js
lib/sanitize.js
package-lock.json
package.json
test/nofollow.js
test/packagize.js
test/sanitize.js
test/youtube.js

- Added a plugin that adds rel=nofollow to links and does no more.
- Added an option to control if the plugin is loaded, defaulted to true, and documented the option.
- Wrote tests to verify that the rel attr is added, and that the option is respected.
- Added `rel` to the allowed list of attributes in the sanitizer.

feature: add rel=nofollow to links if the `nofollow` option is set

---

.travis.yml
lib/sanitize.js
marky.json
package-lock.json
package.json
test/fixtures/basic.md
test/sanitize.js
test/youtube.js

* fix: fixing injection vulnerabilities in render
* fix: removed style attribute support on img elements
* fix: added validation of iframe url hostnames
* fix: fixed fixture to use urls that are parseable by url.parse
* fix: removed brittle regex and added literal string matching for hostnames
* fix: removed node 6 support
* fix: added fixture for style attribute removal
* fix: added test for style attribute removal from img elements
> n/a
* n/a

Fix injection vulnerabilities
