npm/marky-markdown

- index.js
- lib/render.js
- package.json
- test/fixtures.js
- test/index.js
By preventing highlight.js from performing superfluous language detection.
@zeke: not sure if you wanted these debugs in there from the original PR, I'm happy to delete them if not. I like noisy tests but not everyone does :-)
> Fixing syntax highlighting infinite loop

- lib/headings.js
- lib/render.js
- test/index.js
> use short hash on deep links

- lib/render.js
- package.json
* added haxe and nginx grammars.
* changed how mappings work, adding support for erb.
> added haxe, nginx, and erb

- README.md
- bin/marky-markdown.js
- package.json
> Don't prettify the output in CLI

- package.json
Fixes #42
Fixes #622
The tests all pass, wheee!
This pull request is identical to https://github.com/npm/marky-markdown/pull/52 but without merge conflicts.
> Bumping markdown-it dependency

- package.json
> bump cheerio minor version

- .travis.yml
- package.json
this is to help with https://github.com/npm/docs/pull/414
> support node versions 4 and 5

- README.md
> add codeclimate, travis, and david badges to readme

- package.json
> bump lodash to 3.10.1

- lib/cleanup.js
- lib/github.js
- test/fixtures/github.md
- test/index.js
An exception was being thrown on the page:
https://staging.npmjs.com/package/gekoq
Because of the line:
```gfm
```
> an exception was being thrown if an image-style tag did not contain a URL

- README.md
- lib/render.js
- package.json
- test/fixtures/github.md
- test/index.js
replacing #60 cc @patriciarealini
> add emoji support via markdown-it-emoji plugin

- CHANGELOG.md
- package.json
> version 6.0.0

- README.md
The dependencies listed in the README aren't all up to date, so here's a commit to fix that.
> Update README's dependencies list to reflect current project state

- package.json
> Unfreeze github-url-to-object's semver entry

- package.json
fixes #176 
waiting on tests from readme-tester
> bump highlights

- .npmignore
fixes #222 
still very much open to discussion, but while i had the thought, i figured i'd stand this up
> add an npm ignore

- .travis.yml
- README.md
> update and document Node version support

- CHANGELOG.md
- README.md
- package.json
> [WIP] 9.0.0

- lib/plugin/heading-links.js
- lib/sanitize.js
> use octicon octicon-link instead of deep-link-icon

- lib/plugin/heading-links.js
- lib/sanitize.js
- test/headings.js
- test/htmlheading.js
> add `aria-hidden=true` to adding headings

- lib/plugin/heading-links.js
> switch order of attrs on added heading link

- lib/sanitize.js
> allow style attr on img tag

- package.json
> Remove standard-format, use standard --fix now

- lib/plugin/packagize.js
- package.json
- test/markdown.js
> Don't needlessly escape characters in regular expressions

- lib/plugin/github.js
- test/fixtures/github.md
- test/repo-github.js
> Replace github paths in `html_inline` links/images

- index.js
- package.json
- test/marky.js
> Enforce that if options are passed, they must be an object

- lib/plugin/github.js
- test/repo-github.js
> fix(github): use default branch instead of hardcoding `master`

- index.js
- lib/sanitize.js
- test/headings.js
- test/sanitize.js
cherry-picked-and-conflict-resolved version of the change in #357
> fix(sanitize): prefix ids from user generated html

- package.json
Thought maybe with there being a formal GFM spec now that a couple of keywords might help for discoverability
> Add a couple of keywords to the package.json

- package.json
This way it gets updated in the tagged commit rather than having to go in a future commit.
> use version rather than postversion for bumping marky.json

- CHANGELOG.md
> Update changelog for 10.0.1

- lib/plugin/github.js
- package-lock.json
- test/repo-github.js
Oops, in a multi-line HTML block, we were accidentally discarding the content of the block on any lines prior to the one in which the rewriting occurs.
Fixes #404
> Make github package-relative URL rewriting work in multi-line HTML blocks

- lib/sanitize.js
- package-lock.json
- test/fixtures/htmlheadingalign.md
- test/sanitize.js
Allows the align attribute on header elements.
> feat: allow heading alignment
